config/routes.rb
Inzomb::Application.routes.draw do
  
  get "image/index"
  post "image/new" => "image#create"
  get "image/upvote" => "image#upvote"
  get "image/downvote" => "image#downvote"
  get "image/votes" => "image#votes"
  get "image/new"
  get "sessions/new"

  get "users/new"
  
  get "upload" => "image#new", :as => "upload"
  
  get "images" => "image#index", :as => "images"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  

  root :to => "image#index"
  resources :users
  resources :sessions
  resources :image
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :images, :foreign_key => :image_id

end

app/models/images.rb
class Images < ActiveRecord::Base
  belongs_to :user
  has_many :votes, :foreign_key => :image_id
  has_many :comments, :foreign_key => :image_id

  validates_attachment_presence :image
  validates_attachment_size :image, :in => 1..3000000


  has_attached_file :image,
    :styles => { :thumb => "100x100>", :large => "800x800"},
    :storage => :s3,
      :s3_credentials => S3_CREDENTIALS,
      :path => ":attachment/:id/:style.:extension"

  def vote_exists(user)
    upvote_exists(user) || downvote_exists
  end
  def upvote_exists(user)
    return false if user.nil?
    self.votes.exists?(:user_id => user.id, :upvote => true)
  end

  def downvote_exists(user)
    return false if user.nil?
    self.votes.exists?(:user_id => user.id, :upvote => false)
  end

  def upvote
    self.upscore += 1
    self.save
  end
  def downvote
    self.downscore -= 1
    self.save
  end
  def score
    self.upscore
  end
  def self.ten_most_recent
    return order("created_at desc").limit(10)
  end
  def self.ten_most_votes
    return order("upscore desc").limit(10)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :images
    has_many :votes, :foreign_key => :image_id
    has_many :comments, :foreign_key => :image_id

    attr_accessible :name, :email, :password, :password_confirmation
    
    attr_accessor :password
    before_save :encrypt_password
    
    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :name
    validates_uniqueness_of :name
    validates_uniqueness_of :email, :unless => Proc.new {|a| a.email.blank?}
    
    def self.authenticate(name, password)
      user = find_by_name(name)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
    
    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :images, :foreign_key => :image_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  @home =  {:controller => :image, :action => :index}
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  before_filter :authenticate, :except => [:index, :votes, :recent]
  
  def authenticate
    if !current_user
      redirect_to :controller => :sessions, :action => :new, :notice => "Please login before uploading image"
    end
  end
  
  def index
    recent
  end
  def recent
    if current_user.nil?
      @logged = false
    end
    @category = :recent
    @images = Images.ten_most_recent
  end
  def votes
    @category = :votes
    @images = Images.ten_most_votes
    render :index
  end  
  def upvote
    image = Images.find_by_id(params[:id])
    image.upvote
    Vote.create!( :user => current_user, :images => image, :upvote => true)
    redirect_to images_path
  end
  def downvote
    image = Images.find_by_id(params[:id])
    image.downvote
    Vote.create!( :user => current_user, :images => image, :upvote => false)
    redirect_to images_path
  end
  def create
    @image = Images.new(params[:image])
    @image.user_id = current_user.id
    @image.upscore = 0
    @image.downscore = 0
    if @image.save
      redirect_to :action => :index, :notice => "Image Successfully Uploaded"
    else
      render "new"
    end
    
  end
  def new
    @image = Images.new
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  def create
    user = User.authenticate(params[:name],params[:password])
    if user
      session[:user_id] = user.id
      redirect_to "/image/index", :notice => "Logged in"
    else
      flash[:error] = "Invalid username or password"
      render "new", :notice => "Invalid username or password"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to "/image/index", :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to  "/image/new", :notice => "Thanks for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/image/index.html.erb
<%= javascript_include_tag "http://gettopup.com/releases/latest/top_up-min.js?fast_mode=1" %>
<% @images.each do |image| %>
    <div id='image_post'>
      <div id='voting_layout' class="halign">
          <% if image.upvote_exists(current_user) %>
              <%= link_to   image_tag("up_voted.png") %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= link_to image_tag("down_arrow.png"), {:action => :downvote, :id => image.id} %>
          <% elsif image.downvote_exists(current_user) %>
                <%= link_to   image_tag("up_arrow.png") %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= link_to image_tag("down_voted.png"), {:action => :downvote, :id => image.id} %>
          <% else %>
                <%= link_to   image_tag("up_arrow.png", :mouseover => "up_voted.png"), {:action => :upvote, :id => image.id} %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= link_to image_tag("down_arrow.png", :mouseover => "down_voted.png"), {:action => :downvote, :id => image.id} %>
          <% end %>
          </div>
      </div>
      <div id='image_post' class="halign">

	<span id='image_top'>	
		<span id='image_username'> 
			<%= image.user.name %> 
		</span>
		<span id='image_caption'>
			<%= image.caption %>
		</span>
	</span>
	<div id='image_square' class='image_resizer'> 
		<%= link_to(image_tag(image.image.url(:large)), image.image.url ) unless image.image.nil? %>
	</div>
	<span id='image_time'>
		Posted <%= time_ago_in_words(image.created_at) %> ago.
	</span><br>
</div>
<br>
<% end %>

app/views/image/new.html.erb
<div id='signup'>
<%= form_for :image, :html => { :multipart => true } do |image| %>
<% if @image.errors.any? %>
    <div class="error_messages">
      <h2>Uh oh!</h2>
      <ul>
        <% for message in @image.errors.full_messages %>
          -<%= message %><br>
        <% end %>
      </ul>
    </div>
  <% end %>
Choose Image: <%= image.file_field :image %><br>
Caption:<br> <%= image.text_field :caption %><br>
<p class="button"><%= image.submit %></p>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inzomb </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body onclick = 'TopUp.close()' >

<div id="banner">
  <span id="banner_image"> <%= image_tag "banner2.PNG" %>   </span>
  <%= render 'shared/navbar' %>
</div>
        <div id="main">

		<div id="categories">
			<%= link_to_unless_current "Most Recent", images_path %> | 
			<%= link_to_unless_current "Top Votes", :controller => :image, :action => :votes %>
		</div>
		<div id="content">
			<%= yield %> 
		</div>
	</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<div id="navbar_right">
	
  		<% if current_user %>
    		<span id='image_username'><%= current_user.name %></span> |   
    		<%= link_to "Logout", logout_path %> | 
			<%= link_to "Upload Image", upload_path %>
  		<% else %>
    		<%= link_to "Signup", signup_path %> |
    		<%= link_to "Login", login_path %>
  		<% end %>
	
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= 	user.name %><br>
<% end %>

app/views/users/new.html.erb
<div id="signup">
<h1>Signup</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Uh oh!</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          -<%= message %><br>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
    <p><%= f.label :name, "Name "%><br>
    <%= f.text_field :name %></p>

    <p><%= f.label :password, "Password" %><br>
    <%= f.password_field :password %></p>
  
	
    <p><%= f.label :password_confirmation, "Retype Password"%><br>
    <%= f.password_field :password_confirmation %></p>
	
  
    <p><%= f.label :email %><br>
    <%= f.email_field :email %></p>

  <p class="button"><%= f.submit %></p>
<% end %>
</div>